version: "3"

services:
  app:
    image: nicolkill/fullstack-interview-test:latest
    ports:
      - 4000:4000
    volumes:
      - .:/app
    networks:
      - default
      - proxy
    environment:
      PORT: 4000
      NODE_ENV: development

networks:
  proxy:
    external: true
